
print ("===========Masukan Data Diri Anda===========")
Nama_Lengkap = input('masukan Nama_Lengkap :')
Nama_Panggilan = input('masukan Nama_Panggilan :')
Tanggal_Lahir = input('masukan Tanggal_Lahir :')
Tempat_Lahir = input('masukan Tempat_Lahir :')
Jenis_Kelamin = input('masukan Jenis_Kelamin :')
Alamat_Lengkap = input('masukan Alamat_Lengkap :')
Nomor_Telepon = input('masukan Nomor_Telepon :')
Email = input('masukan Email :')
Kewarganegaraan = input('masukan Kewarganegaraan :')
Agama = input('masukan Agama :')
Status_Pernikahan = input('masukan Status_Pernikahan :')
Pekerjaan = input('masukan Pekerjaan :')
Pendidikan_Terakhir = input('masukan Pendidikan_Terakhir :')
Hobi = input('masukan Hobi :')
Golongan_Darah = input('masukan Golongan_Darah :')
Bahasa_yang_Dikuasai = input('masukan Bahasa_yang_Dikuasai :')
Nama_Ayah = input('masukan Nama_Ayah :')
Nama_Ibu = input('masukan Nama_Ibu :')
Keahlian_Khusus = input('masukan Keahlian_Khusus :')
Cita_Cita = input('masukan Cita_Cita :')



print("\n========== Data Diri Anda ==========")
print(f"Nama Lengkap        : {Nama_Lengkap}")
print(f"Nama Panggilan      : {Nama_Panggilan}")
print(f"Tanggal Lahir       : {Tanggal_Lahir}")
print(f"Tempat Lahir        : {Tempat_Lahir}")
print(f"Jenis Kelamin       : {Jenis_Kelamin}")
print(f"Alamat Lengkap      : {Alamat_Lengkap}")
print(f"Nomor Telepon       : {Nomor_Telepon}")
print(f"Email               : {Email}")
print(f"Kewarganegaraan     : {Kewarganegaraan}")
print(f"Agama               : {Agama}")
print(f"Status Pernikahan   : {Status_Pernikahan}")
print(f"Pekerjaan           : {Pekerjaan}")
print(f"Pendidikan Terakhir : {Pendidikan_Terakhir}")
print(f"Hobi                : {Hobi}")
print(f"Golongan Darah      : {Golongan_Darah}")
print(f"Bahasa yang Dikuasai: {Bahasa_yang_Dikuasai}")
print(f"Nama Ayah           : {Nama_Ayah}")
print(f"Nama Ibu            : {Nama_Ibu}")
print(f"Keahlian Khusus     : {Keahlian_Khusus}")
print(f"Cita-Cita           : {Cita_Cita}")
print("===================================")