print("========== Masukkan Data Anda ==========")

# Mengumpulkan data
Nama_Lengkap = input("Nama Lengkap            : ")
Umur = input("Umur                   : ")
Pekerjaan_Sekarang = input("Pekerjaan Sekarang     : ")
Perusahaan = input("Perusahaan             : ")
Pengalaman_Kerja = input("Pengalaman Kerja (tahun): ")
Pendidikan_Terakhir = input("Pendidikan Terakhir    : ")
Keahlian_Teknis = input("Keahlian Teknis        : ")
Bahasa_Pemrograman = input("Bahasa Pemrograman     : ")
Proyek_Terbesar = input("Proyek Terbesar        : ")
Sertifikasi = input("Sertifikasi            : ")
Hobi = input("Hobi                   : ")
Bahasa_Dikuasai = input("Bahasa yang Dikuasai   : ")
Lokasi_Tinggal = input("Lokasi Tinggal         : ")
Kewarganegaraan = input("Kewarganegaraan        : ")
Email = input("Email                  : ")
Nomor_Telepon = input("Nomor Telepon          : ")
LinkedIn = input("LinkedIn Profile       : ")
Github = input("Github Profile         : ")
Cita_Cita = input("Cita-Cita              : ")

# Menampilkan data dengan format rapi
print("\n========== Data Anda ==========")
print("Nama Lengkap            : " + Nama_Lengkap)
print("Umur                   : " + Umur)
print("Pekerjaan Sekarang     : " + Pekerjaan_Sekarang)
print("Perusahaan             : " + Perusahaan)
print("Pengalaman Kerja (tahun): " + Pengalaman_Kerja)
print("Pendidikan Terakhir    : " + Pendidikan_Terakhir)
print("Keahlian Teknis        : " + Keahlian_Teknis)
print("Bahasa Pemrograman     : " + Bahasa_Pemrograman)
print("Proyek Terbesar        : " + Proyek_Terbesar)
print("Sertifikasi            : " + Sertifikasi)
print("Hobi                   : " + Hobi)
print("Bahasa yang Dikuasai   : " + Bahasa_Dikuasai)
print("Lokasi Tinggal         : " + Lokasi_Tinggal)
print("Kewarganegaraan        : " + Kewarganegaraan)
print("Email                  : " + Email)
print("Nomor Telepon          : " + Nomor_Telepon)
print("LinkedIn Profile       : " + LinkedIn)
print("Github Profile         : " + Github)
print("Cita-Cita              : " + Cita_Cita)
print("===================================")
